name: Build and Deploy
on: [push]
jobs:
  checkout:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout 🛎️
        uses: actions/checkout@v2.3.1

  build:
    runs-on: node:12
      - name: Install and Build 🔧
        run: |
          make install

  deploy:
    runs-on: ubuntu-latest
      - name: Deploy 🚀
        uses: JamesIves/github-pages-deploy-action@4.1.5
        with:
          branch: gh-pages # The branch the action should deploy to.
          folder: designer # The folder the action should deploy.